### ISSUE TITLE
有锁屏密码的时候远程黑屏

### ISSUE THREAD

**Issue by Nothend** [wsvn53/scrcpy-mobile#10]
大佬你好，软件很好用，感谢提供这么好的软件。就是有个小问题，安卓手机有锁屏密码，进行远程的时候，ios端就黑屏了，没有出现让输入锁屏密码的界面，取消锁屏密码就可以了 。这个可以解决吗？

**Comment by wsvn53** [comment]
你好，这是 Android 自身的限制，目前无解，但新版本增加了长按唤起键盘，你可以在需要输入密码的地方唤起 iOS 的键盘进行输入，例如这样：
![2022-09-03 16 02 04](https://user-images.githubusercontent.com/912204/188261919-6c118031-daad-4d8f-8e84-6e162baf7cf7.jpg)

![2022-09-03 16 02 08](https://user-images.githubusercontent.com/912204/188261876-6299d4cf-daaf-486c-a259-acde676db392.jpg)

**Comment by Nothend** [comment]
> 你好，这是 Android 自身的限制，目前无解，但新版本增加了长按唤起键盘，你可以在需要输入密码的地方唤起 iOS 的键盘进行输入，例如这样： ![2022-09-03 16 02 04](https://user-images.githubusercontent.com/912204/188261919-6c118031-daad-4d8f-8e84-6e162baf7cf7.jpg)
> 
> ![2022-09-03 16 02 08](https://user-images.githubusercontent.com/912204/188261876-6299d4cf-daaf-486c-a259-acde676db392.jpg)

感谢，新功能不错👍🏼
