### ISSUE TITLE
iPad侧边栏触控失效

### ISSUE THREAD

**Issue by CrazyDragons** [wsvn53/scrcpy-mobile#14]
全屏模式正常，但切换成侧边栏后，点击失效，滑动手势也不灵敏，感觉像是侧边栏模式下还是用的全屏模式的坐标位置，导致点击侧边栏的时候，对应点击的位置是全屏模式下右边的空白无效区域。（在以侧边栏模式启动连接时，半分钟内操作正常，之后就出现上述bug）

**Comment by wsvn53** [comment]
这个问题，我在 iPad 模拟器里试了下，没重现出来，求用图文再描述一下重现步骤 😂

**Comment by hugmatj** [comment]
> 全屏模式正常，但切换成侧边栏后，点击失效，滑动手势也不灵敏，感觉像是侧边栏模式下还是用的全屏模式的坐标位置，导致点击侧边栏的时候，对应点击的位置是全屏模式下右边的空白无效区域。（在以侧边栏模式启动连接时，半分钟内操作正常，之后就出现上述bug）

Translation: The full-screen mode is normal, but after switching to the sidebar, the click fails, and the sliding gesture is not sensitive. It feels like the coordinate position of the full-screen mode is still used in the sidebar mode, resulting in the corresponding click position when clicking the sidebar Is the blank invalid area on the right in full-screen mode. (When starting the connection in the sidebar mode, the operation is normal within half a minute, and then the above bug appears)

**Comment by wsvn53** [comment]
Fixed, please update to latest build on testflight.
