### ISSUE TITLE
crash when clicking ... icon on iPadOS

### ISSUE THREAD

**Issue by RoootTheFox** [wsvn53/scrcpy-mobile#17]
The app crashes with the following error when trying to click the circled ... icon in the top right of the app, making you unable to use things like ADB passcode pairing:
```
Exception type: NSGenericException
Reason: Your application has presented a UIAlertController (<UIAlertController: 0x13489a400>) of style UIAlertControllerStyleActionSheet from UINavigationController (<UINavigationController: 0x13486c000>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.
```

iOS Version: iPadOS 14.2
App Version: 1.6
Jailbreak: checkra1n

Crashlog
[2022-12-15_10_51_am.log](https://github.com/wsvn53/scrcpy-mobile/files/10235898/2022-12-15_10_51_am.log)

**Comment by wsvn53** [comment]
Thanks for your feedback. This issue has been resolved, and you can install the newest version via TestFlight link https://testflight.apple.com/join/9ZE6xhRt

Please let me know if the issue is fixed.
