### ISSUE TITLE
[Feature request] Import ADBkeys

### ISSUE THREAD

**Issue by Dfwk** [wsvn53/scrcpy-mobile#18]
When I pair my tablet with my laptop, it works fine until I don't make ADB connection for 1-2 weeks. After that ADB paired device is automatically removed from tablet, so I need to pair it again. To avoid repairing I make ADB connection to tablet every day at night from Raspberry Pi. Also, I use the same adbkey adbkey.pub for both RasPi and laptop.

My suggestion: let user import his own ADBkeys, so in this situation you wouldn't need to re-pair every time.

Tablet: Samsung Tab A7

**Comment by wsvn53** [comment]
Thanks, it sounds like a good feature.

**Comment by wsvn53** [comment]
This feature will be released in v1.8! Please check updates recently.
