### ISSUE TITLE
建议:可以尝试以下H265编码效果如何

### ISSUE THREAD

**Issue by mutsumi63** [wsvn53/scrcpy-mobile#22]
现在很多新点的手机都自带hevc编码器的
可以尝试下效果如果

`https://github.com/Genymobile/scrcpy/issues/3092`

**Comment by wsvn53** [comment]
这个还是需要官方 scrcpy 先支持下，不过目前 iPhone 上 Scrcpy 用了硬件解码后，瓶颈应该不在于编解码效率了，主要还是在于网络延时

**Comment by mutsumi63** [comment]
> https://github.com/Genymobile/scrcpy/issues/3092

https://github.com/Genymobile/scrcpy/issues/3092#issuecomment-1122041023
官方估计暂时不会支持  
h265同码率下大小会不会小一点

**Comment by wsvn53** [comment]
数据量小一点对延时提升意义不，而且看 issue 里提到好像有些设备用了之后延时还更高了

**Comment by mutsumi63** [comment]
scrcpy 2.0 已支持了h265 av1,好像也加了声音的支持
