### ISSUE TITLE
连接安卓手机无法实现控制手机

### ISSUE THREAD

**Issue by Honanhui** [wsvn53/scrcpy-mobile#24]
你好作者，问一下你这个软件在adb模式下连接怎么控制不了安卓手机，就连点击下栏菜单也没反应。是哪里出错了呢？求解。ios端是16.3 安卓是miui13.07版本

**Comment by Honanhui** [comment]
![Uploading FAED8FF5-4BC4-4888-BFE2-9A6403FEFD41.jpeg…]()

**Comment by Honanhui** [comment]
![16D3166F-96B5-430A-9599-13BD4EBB41E4](https://user-images.githubusercontent.com/101395925/216812139-6dd0218e-dcb3-4d08-a5be-1465e617f381.jpeg)
![2EEC98C2-E052-4BAA-AF0C-D61F3B2C85B3](https://user-images.githubusercontent.com/101395925/216812140-e5185780-d2e7-4307-a637-cf75a009dec4.jpeg)

**Comment by wsvn53** [comment]
请确认下开发者选项里这项设置是否正确打开！
![image](https://user-images.githubusercontent.com/912204/216813304-26bdfc6e-ff81-4b7c-a745-dfcf8fee3737.png)
