### ISSUE TITLE
请问如何完成授权操作？

### ISSUE THREAD

**Issue by erdongleon** [wsvn53/scrcpy-mobile#25]
ios手机wifi链接安卓13，显示设备192.168xxx已链接，但是需要授权操作，请在设备接受授权请求。
我的安卓手机是三星s20，电脑端可以wifi scrcpy链接的，git站提示可以配对码配对，但是app上找不到哪儿设置，求助！

**Comment by wsvn53** [comment]
当你首次使用 Scrcpy iOS 端连接的时候，理论上在你三星手机上会弹出一个授权提示，点击允许即可

**Comment by erdongleon** [comment]
感谢大佬，我尝试着删除了所有adb授权之后重新链，跳出来了。
