### ISSUE TITLE
关闭远程以后，Android端网络adb进程也会退出

### ISSUE THREAD

**Issue by Gokou-Ruri** [wsvn53/scrcpy-mobile#26]
断开以后想重连还得重新开启Android设备的adb进程，请教下怎样让adb进程不会自动退出？

**Comment by wsvn53** [comment]
没看懂，你是指断开之后，Android 开发者选项里的 启用 USB 调试被禁用了吗？

**Comment by Gokou-Ruri** [comment]
> 没看懂，你是指断开之后，Android 开发者选项里的 启用 USB 调试被禁用了吗？

嗯，无论是开发者选项启动网络调试，还是用root启动adbd进程都会这样。
iOS端scrcpy启用“断开连接后关闭屏幕”，连接Android，然后断开连接，此时Android设备的adbd进程已经退出（内存中无adbd进程），iOS端无法重连Android设备，必须重新开启网络adb，才能重新连接。
如果不启用“断开连接后关闭屏幕”，则不会复现这个问题。

**Comment by wsvn53** [comment]
1. Android 设备什么型号，系统版本是什么？
2. 通过 adb tcpip 5555 开启无线调试也会出现这个问题吗？
3. 通过桌面端的 Scrcpy 连接后断开，并通过 adb disconnect 主动断开后，能再次连接吗？

**Comment by Gokou-Ruri** [comment]
> 1. Android 设备什么型号，系统版本是什么？
> 2. 通过 adb tcpip 5555 开启无线调试也会出现这个问题吗？
> 3. 通过桌面端的 Scrcpy 连接后断开，并通过 adb disconnect 主动断开后，能再次连接吗？

摩托罗拉 s30 系统是官方国际版Android 11（类原生）
刚才试了下，桌面版v2.15也这样，跟开启网络adb的方式无关，只要启用了“退出后关闭屏幕”，就会自动结束Android设备的adbd进程，不是scrcpy-mobile的问题。
