### ISSUE TITLE
IPv6 支持

### ISSUE THREAD

**Issue by RinChanNOWWW** [wsvn53/scrcpy-mobile#27]
只能通过 IPv4 地址连接，无法通过 IPv6 地址连接。

**Comment by hugmatj** [comment]
> 只能通过 IPv4 地址连接，无法通过 IPv6 地址连接

Translation: Can only connect via IPv4 address, cannot connect via IPv6 address

**Comment by wsvn53** [comment]
@RinChanNOWWW @aininot260 可以在 host 输入 IPv6 地址的时候用 [] 将地址括起来就可以了例如: `[fd5a:cb7a:f87b7:0:d1c:8b89:ed3f:efb2]`
