### ISSUE TITLE
Secondary Display Support

### ISSUE THREAD

**Issue by SE7ENESE** [wsvn53/scrcpy-mobile#29]
I've been using the preview version of SCRCPY Remote for a little over a week now and I'll be honest - The sheer potential for me has been massive and i believe it's a very productive tool. Once I've confirmed the full extent of it's feature set, I won't hesitate to purchase the full version. I've been able to mirror my Samsung s10e's phone screen with touch input on my iPad with this app and I want to be able to go one step further.

![photo_2023-04-04_13-29-48](https://user-images.githubusercontent.com/108288247/231138163-f73946f9-95c8-4da5-89f1-97e90080f1c2.jpg)

In this image attached is a **.bat** script I run on my PC to access the second display on my phone while I'm running Samsung Dex on my PC. The **--display 2** parameter prompts SCRCPY to mirror the secondary screen on my phone and it speeds up the user experience and productivity on my device. Since SCRCPY Remote is based on the PC version of the software, I was hoping it could be implemented so that accessing the Second display would also be possible in the mobile version.

**Comment by wsvn53** [comment]
It has supported add &display-id=2 on URL Scheme, please update to latest TestFlight version.
