### ISSUE TITLE
Plans for scrcpy 2.0

### ISSUE THREAD

**Issue by Petkov0721** [wsvn53/scrcpy-mobile#33]
I am curious if there are any future plans or roadmap for updating scrcpy to version 2.0?

One of the notable features that this new version offers is audio passthrough, which would be a highly beneficial addition. Along with this, the inclusion of h265 or AV1 video encoders could also potentially improve the overall performance. From my personal experience, these encoders not only improve the image quality but also reduce latency.

I believe these upgrades could substantially enhance the user experience. I appreciate your consideration and look forward to your response.

Best Regards.

**Comment by ptxbc** [comment]
期待

**Comment by wsvn53** [comment]
Hi, the iOS version of scrcpy 2.0 has been developed and ready for releasing. However, it is currently awaiting approval from Apple due to the addition of audio support. But you can try it out first by using TestFlight. https://testflight.apple.com/join/9ZE6xhRt

**Comment by TonySeedy** [comment]
> Hi, the iOS version of scrcpy 2.0 has been developed and ready for releasing. However, it is currently awaiting approval from Apple due to the addition of audio support. But you can try it out first by using TestFlight. https://testflight.apple.com/join/9ZE6xhRt

Can you add tunnels feature?
It's extremely responsive (low latency) with high quality

You can see here
https://github.com/Genymobile/scrcpy/issues/100#issuecomment-1284909480
https://github.com/Genymobile/scrcpy/issues/100#issuecomment-1371089441
