### ISSUE TITLE
关于导航按钮菜单(虚拟按键)的建议

### ISSUE THREAD

**Issue by Jacques-Fry** [wsvn53/scrcpy-mobile#36]
adb模式下的导航菜单触发方式能否拓展更多选项？比如：1、长按屏幕底部触发，2、屏幕底部向上滑动触发，3、始终显示，4、关闭，可以默认为当前的触发方式1，如果2的实现较为麻烦的话可以忽略，但至少请让我有关闭这个导航菜单功能的选项。这个菜单作用虽然很大但是有时候很影响操作体验，经常会出现误触的情况，真的很烦！！！如果能根据使用情况来选择是否开启它也算是一个不错的体验。

**Comment by Jacques-Fry** [comment]
另外声音同步输出的功能有了吗，adb模式试了一下还是没声音

**Comment by wsvn53** [comment]
你好，你说的几种方式中 1、3 和 4 都是有的，默认是长按底部触发，可在连接前的选项按钮中选择是否常显示虚拟导航条，另外你建议的底部触发体验不太好，会和 iOS 的 Home Indictor 手势冲突误触。

至于声音支持，已经在最新的 v2.0 支持了，你可以去更新后试试。

**Comment by lisaac** [comment]
一直不知道还有长按能触导航这个操作，试用了一下
方式1.长按底部触发的确会存在一些问题，现象是在远程android上响应「长按」操作，这显然不是我要的操作
方式3.始终存在会导致很多应用的底栏被覆盖，体验很差

想到最好的方案是，实现类似ios系统辅助功能中的辅助触控功能，把导航功能做成悬浮球，可以解决问题
