### ISSUE TITLE
High latency iOS

### ISSUE THREAD

**Issue by shinishiho** [wsvn53/scrcpy-mobile#37]
Hi, I'm using scrcpy-mobile 2.0 on iPhone XR. As the title said, the video latency is absurdly high (2-3 seconds) while the touch input latency feels almost instantaneous.
Is there any fix for this?
Thank you.

**Comment by wsvn53** [comment]
Please check your WiFi latency by ping tool, generally speaking, the delays below 30ms are relatively smooth to use. Or you 
 can change the bitrate to lower value like 1000K to try again.
