### ISSUE TITLE
是否能增加sdncpy的支持

### ISSUE THREAD

**Issue by mutsumi63** [wsvn53/scrcpy-mobile#4]
声音的支持

**Comment by wsvn53** [comment]
咦？为什么关闭了这个 issue，我还正准备调研一下

**Comment by mutsumi63** [comment]
> 咦？为什么关闭了这个 issue，我还正准备调研一下

不好意思啊 ，我还以为可能不太实用 没法加了就关了， 毕竟最低要android10

**Comment by Gokou-Ruri** [comment]
> 咦？为什么关闭了这个 issue，我还正准备调研一下

请求完善声音支持，这个真的太重要了，目前这个软件其它地方没什么缺陷了。

**Comment by wsvn53** [comment]
计划在最近 release 基于 scrcpy 2.0 的版本，到时候即可支持声音
