### ISSUE TITLE
scrcpy-ios v2.0 is not compatible with older

### ISSUE THREAD

**Issue by Ondrashek** [wsvn53/scrcpy-mobile#40]
I cannot join to redroid with a new version scrcpy-ios v2.0 anymore. I am using redroid on server running with older scrcpy. 

Can you add backward compatible in app?

**Comment by wsvn53** [comment]
Sorry for the bug caused by 2.0. Now the app store has updated version 2.1 to solve this issue. Please update to the latest version.

**Comment by Ondrashek** [comment]
2.1 is working now. Thanks 🙂
