### ISSUE TITLE
Build scrcpy-ios/scrcpy-ios.xcodeproj Failed

### ISSUE THREAD

**Issue by ghostcrying** [wsvn53/scrcpy-mobile#46]
Apple M1 Pro  
MacOS 14.0
Xcode Version 15.0 (15A240d)

I encountered this error, how to fix it, this is the code in version 2.0

<img width="1240" alt="截屏2023-11-13 19 30 23" src="https://github.com/wsvn53/scrcpy-mobile/assets/19705592/d53e3085-bdf8-4275-9530-50b405de5733">

**Comment by wsvn53** [comment]
This requires compiling adb_mobile. Please make sure that libadb has been successfully compiled.

**Comment by ghostcrying** [comment]
You are right, my adb library did fail to compile.

The current version of adb-mobile depends on android-tool version 31.0.3, but this version itself fails to compile on M1 Mac os 13~14. I modified adb-mobile/android-tools/vendor/boringssl/crypto/x509 /t_x509.c file in the error report, and then successfully compiled libadb.a. 

But I still hope you can update to the new version as soon as possible.

**Comment by ghostcrying** [comment]
But I got another error when compiling scrcpy-server. Can you help me find out what's going on?

`set -x && \
	export SCRCPY_VERSION=2.0 && \
	export ANDROID_SDK_ROOT=~/Library/Android/sdk && \
	export JAVA_HOME="$(/usr/libexec/java_home --version 1.11)" && \
	export PATH="$JAVA_HOME/bin:$PATH" && \
	cd server && rm -rf scrcpy-* && \
	curl -o scrcpy.zip -L https://github.com/Genymobile/scrcpy/archive/refs/tags/v$SCRCPY_VERSION.zip && \
	unzip scrcpy.zip && find src -name "*.java" -exec cp -v {} scrcpy-$SCRCPY_VERSION/server/{} \; && \
	cd scrcpy-$SCRCPY_VERSION && \
	meson setup x --buildtype=release --strip -Db_lto=true -Dcompile_app=false -Dcompile_server=true && \
	sed -ibak 's/exit/echo/g' server/scripts/build-wrapper.sh && \
	ninja -Cx -v && \
	find . -type f -name "scrcpy-server" -exec cp -v {} .. \;
+ export SCRCPY_VERSION=2.0
+ SCRCPY_VERSION=2.0
+ export ANDROID_SDK_ROOT=/Users/gost/Library/Android/sdk
+ ANDROID_SDK_ROOT=/Users/gost/Library/Android/sdk
++ /usr/libexec/java_home --version 1.11
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

+ export JAVA_HOME=
+ JAVA_HOME=
+ export PATH=/bin:/opt/homebrew/opt/openjdk/bin:/Users/gost/Downloads/CubismSdkForNative-4-r.7/Samples/Cocos2d-x/thirdParty/cocos2d/templates:/Users/gost/Downloads/CubismSdkForNative-4-r.7/Samples/Cocos2d-x/thirdParty:/Users/gost/Downloads/CubismSdkForNative-4-r.7/Samples/Cocos2d-x/thirdParty/cocos2d/tools/cocos2d-console/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/gost/go/bin
+ PATH=/bin:/opt/homebrew/opt/openjdk/bin:/Users/gost/Downloads/CubismSdkForNative-4-r.7/Samples/Cocos2d-x/thirdParty/cocos2d/templates:/Users/gost/Downloads/CubismSdkForNative-4-r.7/Samples/Cocos2d-x/thirdParty:/Users/gost/Downloads/CubismSdkForNative-4-r.7/Samples/Cocos2d-x/thirdParty/cocos2d/tools/cocos2d-console/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/gost/go/bin
+ cd server
+ rm -rf scrcpy-2.0 scrcpy-server
+ curl -o scrcpy.zip -L https://github.com/Genymobile/scrcpy/archive/refs/tags/v2.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  460k    0  460k    0     0  51235      0 --:--:--  0:00:09 --:--:--  120k
+ unzip scrcpy.zip
Archive:  scrcpy.zip
f1b2d6bbbb5afd1f95913a49b94eda7cfb85226b
   creating: scrcpy-2.0/
   creating: scrcpy-2.0/.github/
   creating: scrcpy-2.0/.github/ISSUE_TEMPLATE/
  inflating: scrcpy-2.0/.github/ISSUE_TEMPLATE/bug_report.md  
  inflating: scrcpy-2.0/.github/ISSUE_TEMPLATE/feature_request.md  
  inflating: scrcpy-2.0/.gitignore   
  inflating: scrcpy-2.0/FAQ.md       
  inflating: scrcpy-2.0/LICENSE      
  inflating: scrcpy-2.0/README.md    
   creating: scrcpy-2.0/app/
   creating: scrcpy-2.0/app/data/
   creating: scrcpy-2.0/app/data/bash-completion/
  inflating: scrcpy-2.0/app/data/bash-completion/scrcpy  
  inflating: scrcpy-2.0/app/data/icon.ico  
  inflating: scrcpy-2.0/app/data/icon.png  
  inflating: scrcpy-2.0/app/data/icon.svg  
 extracting: scrcpy-2.0/app/data/open_a_terminal_here.bat  
  inflating: scrcpy-2.0/app/data/scrcpy-console.bat  
  inflating: scrcpy-2.0/app/data/scrcpy-console.desktop  
  inflating: scrcpy-2.0/app/data/scrcpy-noconsole.vbs  
  inflating: scrcpy-2.0/app/data/scrcpy.desktop  
   creating: scrcpy-2.0/app/data/zsh-completion/
  inflating: scrcpy-2.0/app/data/zsh-completion/_scrcpy  
  inflating: scrcpy-2.0/app/meson.build  
   creating: scrcpy-2.0/app/prebuilt-deps/
 extracting: scrcpy-2.0/app/prebuilt-deps/.gitignore  
  inflating: scrcpy-2.0/app/prebuilt-deps/common  
  inflating: scrcpy-2.0/app/prebuilt-deps/prepare-adb.sh  
  inflating: scrcpy-2.0/app/prebuilt-deps/prepare-ffmpeg.sh  
  inflating: scrcpy-2.0/app/prebuilt-deps/prepare-libusb.sh  
  inflating: scrcpy-2.0/app/prebuilt-deps/prepare-sdl.sh  
  inflating: scrcpy-2.0/app/scrcpy-windows.manifest  
  inflating: scrcpy-2.0/app/scrcpy-windows.rc  
  inflating: scrcpy-2.0/app/scrcpy.1  
   creating: scrcpy-2.0/app/src/
   creating: scrcpy-2.0/app/src/adb/
  inflating: scrcpy-2.0/app/src/adb/adb.c  
  inflating: scrcpy-2.0/app/src/adb/adb.h  
  inflating: scrcpy-2.0/app/src/adb/adb_device.c  
  inflating: scrcpy-2.0/app/src/adb/adb_device.h  
  inflating: scrcpy-2.0/app/src/adb/adb_parser.c  
  inflating: scrcpy-2.0/app/src/adb/adb_parser.h  
  inflating: scrcpy-2.0/app/src/adb/adb_tunnel.c  
  inflating: scrcpy-2.0/app/src/adb/adb_tunnel.h  
   creating: scrcpy-2.0/app/src/android/
  inflating: scrcpy-2.0/app/src/android/input.h  
  inflating: scrcpy-2.0/app/src/android/keycodes.h  
  inflating: scrcpy-2.0/app/src/audio_player.c  
  inflating: scrcpy-2.0/app/src/audio_player.h  
  inflating: scrcpy-2.0/app/src/cli.c  
  inflating: scrcpy-2.0/app/src/cli.h  
  inflating: scrcpy-2.0/app/src/clock.c  
  inflating: scrcpy-2.0/app/src/clock.h  
  inflating: scrcpy-2.0/app/src/common.h  
  inflating: scrcpy-2.0/app/src/compat.c  
  inflating: scrcpy-2.0/app/src/compat.h  
  inflating: scrcpy-2.0/app/src/control_msg.c  
  inflating: scrcpy-2.0/app/src/control_msg.h  
  inflating: scrcpy-2.0/app/src/controller.c  
  inflating: scrcpy-2.0/app/src/controller.h  
  inflating: scrcpy-2.0/app/src/coords.h  
  inflating: scrcpy-2.0/app/src/decoder.c  
  inflating: scrcpy-2.0/app/src/decoder.h  
  inflating: scrcpy-2.0/app/src/delay_buffer.c  
  inflating: scrcpy-2.0/app/src/delay_buffer.h  
  inflating: scrcpy-2.0/app/src/demuxer.c  
  inflating: scrcpy-2.0/app/src/demuxer.h  
  inflating: scrcpy-2.0/app/src/device_msg.c  
  inflating: scrcpy-2.0/app/src/device_msg.h  
  inflating: scrcpy-2.0/app/src/events.h  
  inflating: scrcpy-2.0/app/src/file_pusher.c  
  inflating: scrcpy-2.0/app/src/file_pusher.h  
  inflating: scrcpy-2.0/app/src/fps_counter.c  
  inflating: scrcpy-2.0/app/src/fps_counter.h  
  inflating: scrcpy-2.0/app/src/frame_buffer.c  
  inflating: scrcpy-2.0/app/src/frame_buffer.h  
  inflating: scrcpy-2.0/app/src/icon.c  
  inflating: scrcpy-2.0/app/src/icon.h  
  inflating: scrcpy-2.0/app/src/input_events.h  
  inflating: scrcpy-2.0/app/src/input_manager.c  
  inflating: scrcpy-2.0/app/src/input_manager.h  
  inflating: scrcpy-2.0/app/src/keyboard_inject.c  
  inflating: scrcpy-2.0/app/src/keyboard_inject.h  
  inflating: scrcpy-2.0/app/src/main.c  
  inflating: scrcpy-2.0/app/src/mouse_inject.c  
  inflating: scrcpy-2.0/app/src/mouse_inject.h  
  inflating: scrcpy-2.0/app/src/opengl.c  
  inflating: scrcpy-2.0/app/src/opengl.h  
  inflating: scrcpy-2.0/app/src/options.c  
  inflating: scrcpy-2.0/app/src/options.h  
  inflating: scrcpy-2.0/app/src/packet_merger.c  
  inflating: scrcpy-2.0/app/src/packet_merger.h  
  inflating: scrcpy-2.0/app/src/receiver.c  
  inflating: scrcpy-2.0/app/src/receiver.h  
  inflating: scrcpy-2.0/app/src/recorder.c  
  inflating: scrcpy-2.0/app/src/recorder.h  
  inflating: scrcpy-2.0/app/src/scrcpy.c  
  inflating: scrcpy-2.0/app/src/scrcpy.h  
  inflating: scrcpy-2.0/app/src/screen.c  
  inflating: scrcpy-2.0/app/src/screen.h  
  inflating: scrcpy-2.0/app/src/server.c  
  inflating: scrcpy-2.0/app/src/server.h  
   creating: scrcpy-2.0/app/src/sys/
   creating: scrcpy-2.0/app/src/sys/unix/
  inflating: scrcpy-2.0/app/src/sys/unix/file.c  
  inflating: scrcpy-2.0/app/src/sys/unix/process.c  
   creating: scrcpy-2.0/app/src/sys/win/
  inflating: scrcpy-2.0/app/src/sys/win/file.c  
  inflating: scrcpy-2.0/app/src/sys/win/process.c  
   creating: scrcpy-2.0/app/src/trait/
  inflating: scrcpy-2.0/app/src/trait/frame_sink.h  
  inflating: scrcpy-2.0/app/src/trait/frame_source.c  
  inflating: scrcpy-2.0/app/src/trait/frame_source.h  
  inflating: scrcpy-2.0/app/src/trait/key_processor.h  
  inflating: scrcpy-2.0/app/src/trait/mouse_processor.h  
  inflating: scrcpy-2.0/app/src/trait/packet_sink.h  
  inflating: scrcpy-2.0/app/src/trait/packet_source.c  
  inflating: scrcpy-2.0/app/src/trait/packet_source.h  
   creating: scrcpy-2.0/app/src/usb/
  inflating: scrcpy-2.0/app/src/usb/aoa_hid.c  
  inflating: scrcpy-2.0/app/src/usb/aoa_hid.h  
  inflating: scrcpy-2.0/app/src/usb/hid_keyboard.c  
  inflating: scrcpy-2.0/app/src/usb/hid_keyboard.h  
  inflating: scrcpy-2.0/app/src/usb/hid_mouse.c  
  inflating: scrcpy-2.0/app/src/usb/hid_mouse.h  
  inflating: scrcpy-2.0/app/src/usb/scrcpy_otg.c  
  inflating: scrcpy-2.0/app/src/usb/scrcpy_otg.h  
  inflating: scrcpy-2.0/app/src/usb/screen_otg.c  
  inflating: scrcpy-2.0/app/src/usb/screen_otg.h  
  inflating: scrcpy-2.0/app/src/usb/usb.c  
  inflating: scrcpy-2.0/app/src/usb/usb.h  
   creating: scrcpy-2.0/app/src/util/
  inflating: scrcpy-2.0/app/src/util/acksync.c  
  inflating: scrcpy-2.0/app/src/util/acksync.h  
  inflating: scrcpy-2.0/app/src/util/audiobuf.h  
  inflating: scrcpy-2.0/app/src/util/average.c  
  inflating: scrcpy-2.0/app/src/util/average.h  
  inflating: scrcpy-2.0/app/src/util/binary.h  
  inflating: scrcpy-2.0/app/src/util/bytebuf.c  
  inflating: scrcpy-2.0/app/src/util/bytebuf.h  
  inflating: scrcpy-2.0/app/src/util/file.c  
  inflating: scrcpy-2.0/app/src/util/file.h  
  inflating: scrcpy-2.0/app/src/util/intmap.c  
  inflating: scrcpy-2.0/app/src/util/intmap.h  
  inflating: scrcpy-2.0/app/src/util/intr.c  
  inflating: scrcpy-2.0/app/src/util/intr.h  
  inflating: scrcpy-2.0/app/src/util/log.c  
  inflating: scrcpy-2.0/app/src/util/log.h  
  inflating: scrcpy-2.0/app/src/util/memory.c  
  inflating: scrcpy-2.0/app/src/util/memory.h  
  inflating: scrcpy-2.0/app/src/util/net.c  
  inflating: scrcpy-2.0/app/src/util/net.h  
  inflating: scrcpy-2.0/app/src/util/net_intr.c  
  inflating: scrcpy-2.0/app/src/util/net_intr.h  
  inflating: scrcpy-2.0/app/src/util/process.c  
  inflating: scrcpy-2.0/app/src/util/process.h  
  inflating: scrcpy-2.0/app/src/util/process_intr.c  
  inflating: scrcpy-2.0/app/src/util/process_intr.h  
  inflating: scrcpy-2.0/app/src/util/rand.c  
  inflating: scrcpy-2.0/app/src/util/rand.h  
  inflating: scrcpy-2.0/app/src/util/str.c  
  inflating: scrcpy-2.0/app/src/util/str.h  
  inflating: scrcpy-2.0/app/src/util/strbuf.c  
  inflating: scrcpy-2.0/app/src/util/strbuf.h  
  inflating: scrcpy-2.0/app/src/util/term.c  
  inflating: scrcpy-2.0/app/src/util/term.h  
  inflating: scrcpy-2.0/app/src/util/thread.c  
  inflating: scrcpy-2.0/app/src/util/thread.h  
  inflating: scrcpy-2.0/app/src/util/tick.c  
  inflating: scrcpy-2.0/app/src/util/tick.h  
  inflating: scrcpy-2.0/app/src/util/vecdeque.h  
  inflating: scrcpy-2.0/app/src/util/vector.h  
  inflating: scrcpy-2.0/app/src/v4l2_sink.c  
  inflating: scrcpy-2.0/app/src/v4l2_sink.h  
  inflating: scrcpy-2.0/app/src/version.c  
  inflating: scrcpy-2.0/app/src/version.h  
   creating: scrcpy-2.0/app/tests/
  inflating: scrcpy-2.0/app/tests/test_adb_parser.c  
  inflating: scrcpy-2.0/app/tests/test_binary.c  
  inflating: scrcpy-2.0/app/tests/test_bytebuf.c  
  inflating: scrcpy-2.0/app/tests/test_cli.c  
  inflating: scrcpy-2.0/app/tests/test_clock.c  
  inflating: scrcpy-2.0/app/tests/test_control_msg_serialize.c  
  inflating: scrcpy-2.0/app/tests/test_device_msg_deserialize.c  
  inflating: scrcpy-2.0/app/tests/test_str.c  
  inflating: scrcpy-2.0/app/tests/test_strbuf.c  
  inflating: scrcpy-2.0/app/tests/test_vecdeque.c  
  inflating: scrcpy-2.0/app/tests/test_vector.c  
   creating: scrcpy-2.0/assets/
  inflating: scrcpy-2.0/assets/screenshot-debian-600.jpg  
  inflating: scrcpy-2.0/build.gradle  
  inflating: scrcpy-2.0/bump_version  
   creating: scrcpy-2.0/config/
  inflating: scrcpy-2.0/config/android-checkstyle.gradle  
   creating: scrcpy-2.0/config/checkstyle/
  inflating: scrcpy-2.0/config/checkstyle/checkstyle.xml  
  inflating: scrcpy-2.0/cross_win32.txt  
  inflating: scrcpy-2.0/cross_win64.txt  
   creating: scrcpy-2.0/doc/
  inflating: scrcpy-2.0/doc/audio.md  
  inflating: scrcpy-2.0/doc/build.md  
  inflating: scrcpy-2.0/doc/control.md  
  inflating: scrcpy-2.0/doc/develop.md  
  inflating: scrcpy-2.0/doc/device.md  
  inflating: scrcpy-2.0/doc/hid-otg.md  
  inflating: scrcpy-2.0/doc/linux.md  
  inflating: scrcpy-2.0/doc/macos.md  
  inflating: scrcpy-2.0/doc/recording.md  
  inflating: scrcpy-2.0/doc/shortcuts.md  
  inflating: scrcpy-2.0/doc/tunnels.md  
  inflating: scrcpy-2.0/doc/v4l2.md  
  inflating: scrcpy-2.0/doc/video.md  
  inflating: scrcpy-2.0/doc/window.md  
  inflating: scrcpy-2.0/doc/windows.md  
  inflating: scrcpy-2.0/gradle.properties  
   creating: scrcpy-2.0/gradle/
   creating: scrcpy-2.0/gradle/wrapper/
  inflating: scrcpy-2.0/gradle/wrapper/gradle-wrapper.jar  
  inflating: scrcpy-2.0/gradle/wrapper/gradle-wrapper.properties  
  inflating: scrcpy-2.0/gradlew      
  inflating: scrcpy-2.0/gradlew.bat  
  inflating: scrcpy-2.0/install_release.sh  
  inflating: scrcpy-2.0/meson.build  
  inflating: scrcpy-2.0/meson_options.txt  
  inflating: scrcpy-2.0/release.mk   
 extracting: scrcpy-2.0/release.sh   
  inflating: scrcpy-2.0/run          
   creating: scrcpy-2.0/scripts/
  inflating: scrcpy-2.0/scripts/run-scrcpy.sh  
   creating: scrcpy-2.0/server/
  inflating: scrcpy-2.0/server/.gitignore  
  inflating: scrcpy-2.0/server/build.gradle  
  inflating: scrcpy-2.0/server/build_without_gradle.sh  
  inflating: scrcpy-2.0/server/meson.build  
  inflating: scrcpy-2.0/server/proguard-rules.pro  
   creating: scrcpy-2.0/server/scripts/
  inflating: scrcpy-2.0/server/scripts/build-wrapper.sh  
   creating: scrcpy-2.0/server/src/
   creating: scrcpy-2.0/server/src/main/
  inflating: scrcpy-2.0/server/src/main/AndroidManifest.xml  
   creating: scrcpy-2.0/server/src/main/aidl/
   creating: scrcpy-2.0/server/src/main/aidl/android/
   creating: scrcpy-2.0/server/src/main/aidl/android/content/
  inflating: scrcpy-2.0/server/src/main/aidl/android/content/IOnPrimaryClipChangedListener.aidl  
   creating: scrcpy-2.0/server/src/main/aidl/android/view/
  inflating: scrcpy-2.0/server/src/main/aidl/android/view/IRotationWatcher.aidl  
   creating: scrcpy-2.0/server/src/main/java/
   creating: scrcpy-2.0/server/src/main/java/com/
   creating: scrcpy-2.0/server/src/main/java/com/genymobile/
   creating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/AsyncProcessor.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/AudioCapture.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/AudioCaptureForegroundException.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/AudioCodec.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/AudioEncoder.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/AudioRawRecorder.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Binary.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/CleanUp.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Codec.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/CodecOption.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/CodecUtils.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Command.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/ConfigurationException.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/ControlMessage.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/ControlMessageReader.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Controller.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Device.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/DeviceMessage.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/DeviceMessageSender.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/DeviceMessageWriter.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/DisplayInfo.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/FakeContext.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/IO.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Ln.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/LogUtils.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Options.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Point.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Pointer.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/PointersState.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Position.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Server.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Settings.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/SettingsException.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Size.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Streamer.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/StringUtils.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/VideoCodec.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Workarounds.java  
   creating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/ActivityManager.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/ContentProvider.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/InputManager.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/PowerManager.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/ServiceManager.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java  
  inflating: scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/wrappers/WindowManager.java  
   creating: scrcpy-2.0/server/src/test/
   creating: scrcpy-2.0/server/src/test/java/
   creating: scrcpy-2.0/server/src/test/java/com/
   creating: scrcpy-2.0/server/src/test/java/com/genymobile/
   creating: scrcpy-2.0/server/src/test/java/com/genymobile/scrcpy/
  inflating: scrcpy-2.0/server/src/test/java/com/genymobile/scrcpy/BinaryTest.java  
  inflating: scrcpy-2.0/server/src/test/java/com/genymobile/scrcpy/CodecOptionsTest.java  
  inflating: scrcpy-2.0/server/src/test/java/com/genymobile/scrcpy/CommandParserTest.java  
  inflating: scrcpy-2.0/server/src/test/java/com/genymobile/scrcpy/ControlMessageReaderTest.java  
  inflating: scrcpy-2.0/server/src/test/java/com/genymobile/scrcpy/DeviceMessageWriterTest.java  
  inflating: scrcpy-2.0/server/src/test/java/com/genymobile/scrcpy/StringUtilsTest.java  
 extracting: scrcpy-2.0/settings.gradle  
+ find src -name '*.java' -exec cp -v '{}' 'scrcpy-2.0/server/{}' ';'
src/main/java/com/genymobile/scrcpy/Controller.java -> scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Controller.java
src/main/java/com/genymobile/scrcpy/Device.java -> scrcpy-2.0/server/src/main/java/com/genymobile/scrcpy/Device.java
+ cd scrcpy-2.0
+ meson setup x --buildtype=release --strip -Db_lto=true -Dcompile_app=false -Dcompile_server=true
The Meson build system
Version: 1.2.3
Source dir: /Users/gost/Desktop/Scrcpy/scrcpy-mobile_1/porting/server/scrcpy-2.0
Build dir: /Users/gost/Desktop/Scrcpy/scrcpy-mobile_1/porting/server/scrcpy-2.0/x
Build type: native build
Project name: scrcpy
Project version: 2.0
C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.0.40.1)")
C linker for the host machine: cc ld64 1015.7
Host machine cpu family: aarch64
Host machine cpu: aarch64
Program ./scripts/build-wrapper.sh found: YES (/Users/gost/Desktop/Scrcpy/scrcpy-mobile_1/porting/server/scrcpy-2.0/server/./scripts/build-wrapper.sh)
Build targets in project: 2

scrcpy 2.0

  User defined options
    buildtype     : release
    strip         : True
    b_lto         : true
    compile_app   : false
    compile_server: true

Found ninja-1.11.1 at /opt/homebrew/bin/ninja
+ sed -ibak s/exit/echo/g server/scripts/build-wrapper.sh
+ ninja -Cx -v
ninja: Entering directory `x'
[0/1] /Users/gost/Desktop/Scrcpy/scrcpy-mobile_1/porting/server/scrcpy-2.0/server/./scripts/build-wrapper.sh /Users/gost/Desktop/Scrcpy/scrcpy-mobile_1/porting/server/scrcpy-2.0/server server/scrcpy-server release
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/Users/gost/Desktop/Scrcpy/scrcpy-mobile_1/porting/server/scrcpy-2.0/settings.gradle' (/Users/gost/.gradle/caches/7.5/scripts/4g6ucengw406w5p3xne7pf3a4).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
FAILED: server/scrcpy-server 
/Users/gost/Desktop/Scrcpy/scrcpy-mobile_1/porting/server/scrcpy-2.0/server/./scripts/build-wrapper.sh /Users/gost/Desktop/Scrcpy/scrcpy-mobile_1/porting/server/scrcpy-2.0/server server/scrcpy-server release
ninja: build stopped: subcommand failed.
make: *** [scrcpy-server] Error 1
`

**Comment by wsvn53** [comment]
Here are some adivces from ChatGPT. You can try:

It appears you're encountering a build error related to Gradle, a popular build automation tool. The error message indicates an issue with the Gradle cache or possibly an incompatibility in the Java version used.

Here are some steps you can try to resolve this issue:

1. **Clear Gradle Cache**: Sometimes, the Gradle cache gets corrupted. You can clear the cache by deleting the `.gradle` folder in your user directory (in your case, `/Users/gost/.gradle`).

2. **Check Java Version**: The error `Unsupported class file major version 65` suggests that the Java version used is not compatible with the Gradle version. Java class file version 65 corresponds to Java 17. Make sure the Java version installed on your machine is compatible with the Gradle version you are using. You might need to either update Java or change the Java version used by Gradle.

3. **Update Gradle**: If you're using an older version of Gradle, consider updating it. Newer versions of Gradle might have better compatibility with newer Java versions.

4. **Re-import the Project**: If you're using an IDE, try re-importing the project after clearing the cache and adjusting the Java version.

5. **Check Gradle Wrapper**: If your project uses Gradle Wrapper, ensure that the `gradle-wrapper.properties` file in your project points to the correct Gradle version.

6. **Consult Documentation/Forums**: If the issue persists, consult the Gradle documentation or relevant forums for more specific guidance related to the error.

Remember to backup important files before making changes. If you are part of a team, ensure that changes made are consistent across all development
