### ISSUE TITLE
2.x版本 App 启动闪退

### ISSUE THREAD

**Issue by xxhhlk** [wsvn53/scrcpy-mobile#49]
iOS 14.3 软件是 TF 版本 2.3(1)
[scrcpylog.zip](https://github.com/wsvn53/scrcpy-mobile/files/13549044/scrcpylog.zip)
这问题有好长时间了 2.0版本出来就是闪退

**Comment by ZYMirror** [comment]
> iOS 14.3 软件是 TF 版本 2.3(1) [scrcpylog.zip](https://github.com/wsvn53/scrcpy-mobile/files/13549044/scrcpylog.zip) 这问题有好长时间了 2.0版本出来就是闪退

有人说是越狱环境问题，关掉越狱就可以了

**Comment by xxhhlk** [comment]
2.3(2) 在越狱状态可正常使用了
