### ISSUE TITLE
Hope to improve the sensitivity of swipe events

### ISSUE THREAD

**Issue by gawinwong** [wsvn53/scrcpy-mobile#5]
I have tested this app on my ipad pro and huawei p30p with the game named"Harry Potter: Magic Awakened" under a 5400M 5G wifi. No matter what the bitrate is, the latency is acceptable and the touch event  response is fairly timely. But at the same time, swipe events did not perform as well that I can easily feel the mismatch between the swipe position and my finger position.

**Comment by wsvn53** [comment]
Do you provide a video? I need to find out what exactly slow. In addition, it is best to provide a network ping delay from your iPad to Android.
