### ISSUE TITLE
`scrcpy --display-id` 功能支持

### ISSUE THREAD

**Issue by IlIllIl** [wsvn53/scrcpy-mobile#50]
如题，WSA、PC扩展模式、多屏、虚拟副屏等场景下可能需要根据 `adb shell dumpsys display | grep mUniqueId` 指定 Android 屏幕 id `scrcpy --display-id` 投屏控制，添加此功能会很方便。

**Comment by wsvn53** [comment]
已经在 URL Scheme 中支持，请更新最新的 TestFlight 版本
