### ISSUE TITLE
希望增加功能菜单

### ISSUE THREAD

**Issue by kickTiger** [wsvn53/scrcpy-mobile#6]
## 使用场景
增加基本的硬件功能按键，目前没看到这个菜单界面。没有这些功能键，基本上没法使用。可以固定显示在投影的手机界面底部区域。类似用scrcpy实现的投影都具备菜单功能。

## 功能按键
比如返回键，前进键，主页键，音量键，电源键，顶部下拉键。

如果有此功能，麻烦告知开启方式，谢谢作者大大

**Comment by wsvn53** [comment]
请更新 test flight 上发布的最新版本 1.3，长按屏幕最底部区域可以看到常用功能菜单。

https://testflight.apple.com/join/9ZE6xhRt

**Comment by kickTiger** [comment]
> 请更新 test flight 上发布的最新版本 1.3，长按屏幕最底部区域可以看到常用功能菜单。
> 
> https://testflight.apple.com/join/9ZE6xhRt

感谢大佬回复，试用了这个功能有几点建议

## 菜单使用后
- 1.目前菜单是根据机型显示，有些机型的菜单是硬件类型无法显示，必须长按后呼出。
- 2.长按呼出的菜单，点击一次后就消失了，比如多次使用返回键，或者切换键，就没法使用了，只能再次长按呼出功能菜单。这种方法很不方便。

## 建议优化
- 1.某些机型无软按键的，呼出菜单建议可自行选择展开模式，并长期置顶。
- 2.呼出菜单建议可以有一个缩微图标，浮动的图标在右侧或者全屏拖拽的（可拖拽是为了避免挡住系统内容），点击浮动图标可以折叠功能菜单，也可以展开菜单并保持置顶。

**Comment by wsvn53** [comment]
某些机型无法唤出的问题，最近尝试修复了一下，可以看看最新的版本是否还有问题
