### ISSUE TITLE
Demuxer Video Error

### ISSUE THREAD

**Issue by rizalig** [wsvn53/scrcpy-mobile#60]
Help 

DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: metal
DEBUG: Trilinear filtering disabled (not an OpenGL renderer
DEBUG: Demuxer 'video': starting thread
DEBUG: Receiver stopped
DEBUG: quit...
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error

**Comment by fbloise** [comment]
same

**Comment by wsvn53** [comment]
Please help to test the newest version on testflight https://testflight.apple.com/join/9ZE6xhRt

Please let me know, if still errors.

**Comment by fbloise** [comment]
> Please help to test the newest version on testflight https://testflight.apple.com/join/9ZE6xhRt
> 
> Please let me know, if still errors.

Thanks, just test it and it works perfect!!
