### ISSUE TITLE
隔一段时间之后就要重新授权

### ISSUE THREAD

**Issue by ck629** [wsvn53/scrcpy-mobile#62]
昨天下午授权通过之后今天上午再连接就一直失败，拿手机看了发现需要重新授权，请问这正常吗？

**Comment by wsvn53** [comment]
请检查一下开发者选项里面有没有开启 “禁用 adb 超时授权”？如果开启过，那有可能是手机 bug 了，这时候你可以试试电脑上用 scrcpy 连接 tcpip 5555 端口是否正常。

**Comment by ck629** [comment]
> 请检查一下开发者选项里面有没有开启 “禁用 adb 超时授权”？如果开启过，那有可能是手机 bug 了，这时候你可以试试电脑上用 scrcpy 连接 tcpip 5555 端口是否正常。

开发者选项里没有这个选项，去文件里看adb_keys之前的密钥还在。
电脑运行adb tcpip 5555后有返回值，之后用app连接就正常了，此时adb_keys文件没有变化。

**Comment by wsvn53** [comment]
呃，我意思是当手机上连不上 5555 的时候，用电脑上的 scrcpy 试试连接 5555 是否能正常投屏？

**Comment by ck629** [comment]
> 呃，我意思是当手机上连不上 5555 的时候，用电脑上的 scrcpy 试试连接 5555 是否能正常投屏？

好的，下次再出现这个情况的时候我试试，另外我的手机一直用USB线连到电脑上，偶尔也在电脑上用有线方式scrcpy，会是造成问题的原因吗？
但是app能正常连接的时候电脑也可以同时连，没有断过

**Comment by ck629** [comment]
今天又连不上了，电脑adb connect ip:5555连不上手机，需要adb tcpip 5555之后才行

**Comment by wsvn53** [comment]
那这种情况，只能建议你根据设备型号搜一下有没有解决方案，用可能是国内厂商魔改了什么设置。

**Comment by ck629** [comment]
好的，感谢大佬，关单了
