### ISSUE TITLE
安卓版本什么时候发布呢，在线等

### ISSUE THREAD

**Issue by XuanTian-LTD** [wsvn53/scrcpy-mobile#65]
安卓版本什么时候发布呢，在线等

**Comment by wsvn53** [comment]
不好意思，短期可能没有 Android 版本，你可以找找，已经有 Android 开发者开发过类似的替代品

**Comment by XuanTian-LTD** [comment]
> 不好意思，短期可能没有 Android 版本，你可以找找，已经有 Android 开发者开发过类似的替代品

比如有哪些呢？

**Comment by miiwu** [comment]
> 比如有哪些呢？

抛砖引玉：

1. [gitlab.com/las2mile/scrcpy-android](https://gitlab.com/las2mile/scrcpy-android): [scrcpy.apk](https://gitlab.com/las2mile/scrcpy-android/raw/master/release/scrcpy-release.apk)
2. [github.com/huage2580/scrcpy-android](https://github.com/huage2580/scrcpy-android): [scrcpy-lite.apk](https://raw.githubusercontent.com/huage2580/scrcpy-android/master/release/scrcpy-release.apk)

---

2 之于 1，按我理解应该是 fork 关系。

在 HarmonyOS 4.2.0 版本平板上两款均能工作，不过比较年久了，可能会有一些问题 ，不过满足我使用了，先点到为止。

2 有个悬浮窗模式，最终选择了它：一者，避免了全屏时分辨率不匹配有大黑框；二者，悬浮窗可以收起来只留一个标题栏。
