### ISSUE TITLE
Encoder Error

### ISSUE THREAD

**Issue by itsnaufal** [wsvn53/scrcpy-mobile#67]
![IMG_1106](https://github.com/wsvn53/scrcpy-mobile/assets/5900266/2530f089-70d9-420f-8808-2053c5c8fc4d)

As you can see the output video stream is broken and glitched, and this is because the encoder issue (you can read more here https://github.com/Genymobile/scrcpy/issues/4770)

There are a way to fix it, by changing the encoder to --video-encoder='c2.android.avc.encoder' but in the scrcpy mobile app there is no option to change the encoder, i've tried the testflight version but still broken.

so is there an option or please i beg you @wsvn53 to add option to change the encoder.

Thank you

**Comment by wsvn53** [comment]
Added on latest TestFlight update
